### ISSUE TITLE
makeWishNoAggregateVersion misses no more than 3 wishes business rule

### ISSUE THREAD

**Issue by permiakov** [dddinphp/last-wishes#21]
Hi guys. Thanks for the book.

I am wandering where it would be placed "no more than 3 wishes business rule" in case of makeWishNoAggregateVersion?

**Comment by tszymanek** [comment]
If it's a business rule, it should stick to the domain layer as close as possible. There's no other option to tell how many Wishes a User has.

You could try to make WishRepository an abstract class and place a const there and compare the number of Wishes with given UserId with it, but it becomes less clear what your domain ~~constraints~~ invariants are and where to find them.
