### ISSUE TITLE
[Dashboard] Error when loading dashboard. "badgesFrom" method expects an UserId but it is receiving a string instead.

### ISSUE THREAD

**Issue by MyGonBa** [dddinphp/last-wishes#5]
The method "badgesFrom" expects an instance of UserId but the request of the ApplicationService where that method is called from is being created directly with the uuid (string) instead of with the object itself.

According to the implementation, I would say that the method's signature of "badgesFrom" should change to not expect an UserId but a string (the uuid).

**Comment by theUniC** [comment]
Yep! You're right! But instead of changing the method signature of ```badgesFrom``` I would change the Application Service implementation in order to avoid falling on *primitive obsession* and operate always on a domain concept.
